### ISSUE TITLE
3.0.0 / SyntaxError: Unexpected token

### ISSUE THREAD

**Issue by Xairoo** [sindresorhus/grunt-concurrent#102]
3.0.0 gives me an error:

```
Loading "concurrent.js" tasks...ERROR
>> SyntaxError: Unexpected token ...
```
2.3.1 works fine. Haven't looked into it because I downgraded to a working version.

grunt-cli v1.2.0
grunt v1.0.4

**Comment by sindresorhus** [comment]
You need to upgrade Node.js.
