### ISSUE TITLE
Error handelling Multiple flag

### ISSUE THREAD

**Issue by lvl-svasseur** [sindresorhus/grunt-concurrent#36]
I'm using grunt-concurrent v0.5.0

At the end of my Gruntfile I call the following function

```
traceContext();
function traceContext(){
        grunt.log.subhead('Options' );
        grunt.log.writeflags( grunt.option.flags() );

        grunt.log.subhead('Context' );
        grunt.log.writeflags( grunt.config.get('context') );
    }
```

I run the following command line
`grunt build:dist --env=development --local=true``

Before each concurrent task traceContext is called and output 

```
    Options
    Flags: --target=dist, --local, --env=development

    Context
    Flags: public="dist-development", source="app", target="dist", env="development"
```

While concurrent run before each task 

```
    Options
    Flags: --target=dist, --local=--env=development, --env=undefined

    Context
    Flags: public="dist", source="app"
```

Notice here `--local=--env=development`.

**Comment by colinkahn** [comment]
I'm seeing the same thing

**Comment by colinkahn** [comment]
This was an issue for me as well, I installed https://github.com/widgetworks/nopt-grunt-fix which fixed it.
