### ISSUE TITLE
Propagate Exit Status of Child Processes

### ISSUE THREAD

**Issue by swissmanu** [sindresorhus/grunt-concurrent#47]
i run functional test suites in multiple processes using `grunt-concurrent`. it seems that `grunt-concurrent` does not propagate the exit status of any child processes up to the main process when finishing its work.
is there an easy way how i can achieve this or would this be a desirable feature for a future release?

thanks,
manu

**Comment by aaani** [comment]
any updates?

**Comment by plilyft** [comment]
any updates?
