### ISSUE TITLE
Concurrent is not running the tasks registered inside other task

### ISSUE THREAD

**Issue by Valentyn** [sindresorhus/grunt-concurrent#51]
In one of my Grunt tasks I'm dynamically registering several tasks depending on the number of CPU Cores that the system has. After those tasks are created, I can successfully run them using grunt.task.run(<TaskName>) . But when I try to run them using concurrent the error "Warning: Task <TaskName> not found. Use --force to continue.".

**Comment by sindresorhus** [comment]
Use StackOverflow for support questions. And you need to include more information. Gruntfile, etc.
