### ISSUE TITLE
Tasks run in alphabetical order, not the order of the gruntfile

### ISSUE THREAD

**Issue by adavies-github** [sindresorhus/grunt-concurrent#53]
Hi,

There appears to be a bug where grunt-concurrent messes up the execution order of a task. For example, I have this setup:

		concurrent: {
			all: {
				tasks: [
					'concurrent:processJs',
					'concurrent:splitGlobal',
					'concurrent:splitAndWrapLegacy'
				],
				options: {
					limit: 4,
					//logConcurrentOutput: true
				}
			},
			splitGlobal: [
				'csssplit:global',
			],
			splitAndWrapLegacy: [
				'css_wrap:legacy',
				'concat:legacyAndLegacyExtra',
				'csssplit:legacy'
			],
			processJs: [
				'concat:globalJsAngular',
				'concat:globalJsComponents',
				'concat:globalJs',
				'copy:srcJsToTmp',
				'uglify:globalJs',
				'concat:globalJsMin',
				'concat:audiApp',
				'uglify:globalApps',
			]
		},

When I run all three of these tasks concurrently by running concurrent:all, I notice the processJs task executes in this order (I have trimmed the console output):

    Running "concurrent:processJs" (concurrent) task
        
        Running "copy:srcJsToTmp" (copy) task          
        Running "concat:globalJsComponents" (concat) task
        Running "concat:audiApp" (concat) task
        Running "concat:globalJsAngular" (concat) task
        Running "concat:globalJsMin" (concat) task
        Running "concat:globalJs" (concat) task
        Running "uglify:globalApps" (uglify) task
        Running "uglify:globalJs" (uglify) task 

I am running grunt 0.4.5 on Mac OSX 10.10.2. Could you have a look and let me know if there is a solution to this?

Kind regards,
Alex.

**Comment by kevva** [comment]
Running them concurrently means that we can't control the order.
