### ISSUE TITLE
How is possible to run the ionic:serve and watch with concurrent?

### ISSUE THREAD

**Issue by ceoaliongroo** [sindresorhus/grunt-concurrent#61]
[generator-ionic](https://github.com/diegonetto/generator-ionic/) fails, using `grunt-concurrent` for tasks `ionic:serve` and `watch`.  

https://github.com/diegonetto/generator-ionic/blob/master/templates/common/_Gruntfile.js#L514-L515
https://github.com/diegonetto/generator-ionic/blob/master/templates/common/_Gruntfile.js#L308-L314

I could do it with `grunt-parallel`
https://stackoverflow.com/questions/30853177/ionic-cli-exiting-after-grunt-serve/31126471#31126471

Why fail with `grunt-concurrent`?

thanks

**Comment by sindresorhus** [comment]
https://github.com/diegonetto/generator-ionic/issues/210

**Comment by ceoaliongroo** [comment]
Thanks! @sindresorhus
