### ISSUE TITLE
2.0 does not seem compatible with bunyan logger

### ISSUE THREAD

**Issue by malchak** [sindresorhus/grunt-concurrent#62]
Node: v0.10.38

I'm finding that updating from grunt-concurrent 1.0.1 to 2.0.0 breaks the bunyan (v1.4.0) json output formatting in my console.

Output using grunt-concurrent (v1.0.1) with bunyan (v1.4.0):
![screen shot 2015-07-06 at 11 49 57 am](https://cloud.githubusercontent.com/assets/1450296/8531809/bfbd0620-23de-11e5-9e4a-382be2afee83.png)

Output using grunt-concurrent(v2.0.0) with bunyan (v1.4.0):
![screen shot 2015-07-06 at 11 53 17 am](https://cloud.githubusercontent.com/assets/1450296/8531833/ec3f26b0-23de-11e5-82e8-12bd19cd2b7f.png)

I can't seem to pinpoint the change that could cause this.  I'm passing the `process.stdout` object to bunyan like so:

    var CONFIG = require('config');
    var bunyan = require('bunyan');

    module.exports = function (name) {
        return bunyan.createLogger({
          name: name || 'myproject.js',
          stream: process.stdout,
          level: CONFIG.app.logLevel
        });
    };

Is there anything in the new grunt-concurrent version that may alter the way stdout is being passed?

**Comment by sindresorhus** [comment]
2.0.0 no longer inherits the child stream, but instead pipes it so we're able to indent the output. Bunyan probably tries to detect whether it's `process.isTTY` and logs JSON instead. There's probably a way to force normal output in Bunyan. Not really relevant to this plugin though.

**Comment by malchak** [comment]
@sindresorhus Thanks for the clarification!  I'll look into it some more.
