### ISSUE TITLE
Don't work with livereload and multiple watch targets.

### ISSUE THREAD

**Issue by diosney** [sindresorhus/grunt-concurrent#63]
The second watch target trigger the error:

```
 Fatal error: Port 35729 is already in use by another process.

**Comment by sindresorhus** [comment]
Use StackOverflow for support questions. Nothing to do with this task really.

**Comment by diosney** [comment]
Yeh, I know  what the people in SO are saying about this not being possible, but didn't found a related issue here (I didn't a deep search).

My rationale is that since using concurrent watches with livereload enabled is a common use case for this task and a lot of people has this issue, maybe this could be addressed here, something similar as **grunt-focus** did (I don't know if it is possible).
