### ISSUE TITLE
Add history/changelog

### ISSUE THREAD

**Issue by simison** [sindresorhus/grunt-concurrent#65]
Would love to be able to see quickly what's new in 2.0

Thanks!

**Comment by sindresorhus** [comment]
Right here: https://github.com/sindresorhus/grunt-concurrent/commits/master

I keep a clean commit history so the changelog would pretty much just be a copy paste from that. I don't do changelogs for smaller projects like these as the overhead is too high and the need for it too low as there's usually only a few changes in each release and as I said, the commit log is pretty clean.

<img width="638" alt="screen shot 2015-07-12 at 12 16 46" src="https://cloud.githubusercontent.com/assets/170270/8637394/ef8b1454-288f-11e5-9ba4-7819b48ed32e.png">

**Comment by simison** [comment]
Fair enough, that's neat. Thanks!

**Comment by simison** [comment]
BTW, for medium-sized projects you might be interested to check this https://skywinder.github.io/github-changelog-generator/
