### ISSUE TITLE
2.0.0 indentation compatibility issue with karma "dots" reporter

### ISSUE THREAD

**Issue by jimf** [sindresorhus/grunt-concurrent#66]
Not sure if this is an issue here, or simply an interoperability issue with the way the karma "dots" reporter is implemented, but it appears that after upgrading from 1.0.1 to 2.0.0, I'm seeing the indentation whitespace interspersed between the dots coming from the karma "dots" reporter.

Before:
![screen shot 2015-07-14 at 2 57 02 pm](https://cloud.githubusercontent.com/assets/413269/8681996/a3a8be7e-2a38-11e5-8213-07f9c1eb4d58.png)

After:
![screen shot 2015-07-14 at 2 57 42 pm](https://cloud.githubusercontent.com/assets/413269/8682028/bfb06c7a-2a38-11e5-834d-add63fbf41c4.png)

**Comment by jimf** [comment]
Got a chance to look into this further. This is happening because grunt-concurrent uses pad-stdio to statically define a left padding on stdout, regardless of whether the message being outputted contains a linebreak or not. The solution isn't straightforward however, as simply looking for a trailing newline before inserting padding isn't enough (in the case of the dots reporter, you'd end up with a line of dots, followed by padding, followed by a final dot and newline). Trying to reverse the logic and rpad when a trailing newline is encountered doesn't quite solve it either, as the first line will be missing the indentation.

Possible paths to take:
 1. concede defeat and switch to a different reporter
 1. add an option to grunt-concurrent to disable/specify the padding
 1. try to come up with a solution via rpad, etc. and newline inspection
 1. other???

Thoughts?

**Comment by sindresorhus** [comment]
I guess it would be possible to pipe the child process through [pad-stream](https://github.com/sindresorhus/pad-stream), which handles newlines, instead of using `pad-stdio`.

**Comment by jimf** [comment]
Great suggestion, totally worked. I started up a PR, but I feel like I might be missing something with regard to when `logConcurrentOutput` is false. Should it still pad in that case? I've got a wip branch up if you have a sec to take a look: https://github.com/sindresorhus/grunt-concurrent/compare/master...jimf:fix-newline-padding-wip. Thanks!

**Comment by sindresorhus** [comment]
> Should it still pad in that case?

Yes.

> I've got a wip branch up if you have a sec to take a look: master...jimf:fix-newline-padding-wip. Thanks!

Just do a PR. Easier to review ;)
