### ISSUE TITLE
Do not ignore stdin

### ISSUE THREAD

**Issue by tusbar** [sindresorhus/grunt-concurrent#75]
Hey,

When using grunt-concurrent with something like `grunt-nodemon` it would be very interesting to have grunt-concurrent watch the standard input so I could type `rs` to restart the running process with nodemon.

I feel like this used to work with `grunt-concurrent` and now it does not anymore. Is there a reason?

Could we just replace the stdin `'ignore'` with `process.stdin` in the [`spawn` call](https://github.com/sindresorhus/grunt-concurrent/blob/master/tasks/concurrent.js#L27-L32)?

**Comment by sindresorhus** [comment]
Only a search away: https://github.com/sindresorhus/grunt-concurrent/issues?utf8=%E2%9C%93&q=stdin
