### ISSUE TITLE
From ~200ms to ~10s

### ISSUE THREAD

**Issue by JPeer264** [sindresorhus/grunt-concurrent#76]
Why is in my case concurrent slowing down the grunt tasks?
Compared
```grunt
concurrent: {
	concatjs: ['concat:js', 'concat:app', 'concat:vendor']
}
```

to
```grunt
grunt.registerTask('manage:js', [
	'concat:js',
	'concat:app',
	'concat:vendor',
]);
```

I have a much better performance with standard registration.
![cmd](https://cloud.githubusercontent.com/assets/10677263/9812882/dc0c2e9c-5880-11e5-8d07-ce93b209e530.jpg)

**Comment by sindresorhus** [comment]
> Why is in my case concurrent slowing down the grunt tasks?

The task spawns child processes of grunt that runs concurrently. Spawning child processes generally comes with some overhead and launching grunt is very slow, especially on Windows and if you're not on a SSD harddrive. It's not a magic bullet and works best when you have heavy tasks with many files. In your case this task is overkill.
