### ISSUE TITLE
Will fail when using two watch-livereload tasks

### ISSUE THREAD

**Issue by julmot** [sindresorhus/grunt-concurrent#77]
When using grunt-concurrent with two watch-tasks with livereload-option set to true, this task will fail.

**Comment by sindresorhus** [comment]
No, livereload will fail as you're trying to use multiple livereload instances using the same port. You need to set unique ports. In the future please use StackOverflow for support questions.

**Comment by julmot** [comment]
If so a error message would be helpful instead of just "Failed".
