### ISSUE TITLE
An option to allow a task to inherit stdin

### ISSUE THREAD

**Issue by fatfisz** [sindresorhus/grunt-concurrent#82]
I'd like to propose a way to allow a task to inherit `stdin`.

The motivation is that in a `watch` & `nodemon` setup the `watch`-type tasks don't need any input, but it would be nice to be able to pass the `rs` command to `nodemon`.

#### Task options
Apart from providing a task name, there would be an option to provide an array with the name and the options object (similar to `grunt-browserify`):
```js
{
  tasks: ['watch', ['nodemon', { <options> }]]
}
```
This shouldn't break anything existing today.

#### The `inheritStdin` option
This should be a `Boolean`-type value (defaults to `false`).
If `true`, then `process.stdin` would be provided as the `stdin` for the child process instead of `'ignore'`.

**Comment by sindresorhus** [comment]
Not something I'm interested in. Maybe try asking for it on https://github.com/iammerrick/grunt-parallel.

Although, sounds like something that should be fixed in `nodemon`. Maybe do an issue/PR there about ability to pass the `rs` thing non-interactively through a CLI flag.

**Comment by fatfisz** [comment]
I understand that you are not interested in this, just want to clear up what `rs` does - this is a runtime command for restarting whatever `nodemon` is taking care of. From `nodemon` docs:
> Whilst nodemon is running, if you need to manually restart your application, instead of stopping and restart nodemon, you can simply type `rs` with a carriage return, and nodemon will restart your process.

**Comment by zpnk** [comment]
@sindresorhus Hi Sindre, would you mind clarifying why you wouldn't be interested in this kind of option?

I have the exact same use case as @fatfisz: nodemon+watch as tasks being run concurrently. Sometimes it is useful to manually trigger a nodemon restart by typing `rs`. When running nodemon by itself this works fine, when running under grunt-concurrent it does not receive stdin.

This cannot be solved by passing a flag to nodemon as it needs to be trigger-able at runtime.

The solution is passing 'inherit' as the [fd 0 option](https://github.com/sindresorhus/grunt-concurrent/blob/master/tasks/concurrent.js#L39). 

If 'inherit' isn't the best choice as the default option, then it would be super awesome if this was configurable similar to `logConcurrentOutput`. I can get a PR up if you'd be willing to take a look.

**Comment by wshaheer** [comment]
@zpnk From my understanding (although fairly limited), would a better solution be to pass this option individually for each task, in case they have different interpretations for the same flag? E.g

`tasks: [{ name: 'watch', inherit: false }, { name: 'nodemon', inherit:  true }]`
