### ISSUE TITLE
nodemon task doesn't exit

### ISSUE THREAD

**Issue by immo-huneke-zuhlke** [sindresorhus/grunt-concurrent#84]
I'm using grunt-concurrent under Mac OS X El Capitan. I have to run some Protractor tests that require a bunch of node.js servers to be running. My configuration is currently:

            ...
            concurrent: {
                system: {
                    tasks: ['nodemon:api', 'test-e2e-client'],
                    options: {
                        logConcurrentOutput: true,
                        limit: 5
                    }
                }
            },
            ...
            nodemon: {
                api: {
                    script: 'server/server.js',
                    options: {
                        cwd: '../api_server',
                        args: ['dev'],
                        delay: 1000
                    }
                }
            },
            ...

This all works fine, but after the Protractor tests have finished running I want the node process to terminate. Currently it just keeps running and I have to use CTRL-C to stop grunt, which then cleans up the background processes. Is there a recommended way to terminate all concurrent processes when one of them exits?

**Comment by sindresorhus** [comment]
> Is there a recommended way to terminate all concurrent processes when one of them exits?

No

**Comment by immo-huneke-zuhlke** [comment]
Thanks for your quick reply. I have solved the problem by defining a new sequence of tasks that runs the protractor tests and then terminates the background node process.
