### ISSUE TITLE
stderr getting lost in padStream

### ISSUE THREAD

**Issue by lostplan** [sindresorhus/grunt-concurrent#89]
When logConcurrentOutput is enabled no stderr is making it to the console. Remove the stream padding and stderr reappears.

**Comment by sindresorhus** [comment]
Can you provide a minimal runnable example?

The code for `stderr` is exactly the same as `stdout`, so I find it weird that only it would have this issue: https://github.com/sindresorhus/grunt-concurrent/blob/0d76521f09919e97704c45868dc1e86ce1352537/tasks/concurrent.js#L53

**Comment by lostplan** [comment]
Struggling to make a simple repro. The issue arises when one of the tasks calls webpack (via grunt-shell) with the `--progress` flag (which outputs build progress on stderr).

**Comment by sindresorhus** [comment]
Closing for lack of repro.
