### ISSUE TITLE
Concurrent target as part of task list

### ISSUE THREAD

**Issue by sebadom** [sindresorhus/grunt-concurrent#93]
Since i'm experiencing a weird behaviour on my build i thought about asking this..
I have some concurrent target as part of a list of normal grunt tasks, say something like that

```
grunt.registerTask('default', [
  'a:1',
  'b',
  'c',
  'concurrent:target1',
  'a:2',
  'b',
  'c',
   'concurrent:target2'
]);

concurrent:target1: [1,2,3]
concurrent:target2: [4,5,6]
```

If you see its kind of the same pipeline of tasks A-B-C-concurrent, the only thing is that each A(1 and 2) change some configuration values and the rest are run based on that value.
My question is that if all concurrent task within the concurrent target are run before grunt moves to the next one (like if a:2 only runs after all concurrent:target1 is done) because somehow when concurrent:target1 runs, i see the value that should be set by a:2 (which shouldn't supposed to run yet)

Thanks

**Comment by sebadom** [comment]
i think its the same case as #12 Not sure why that is closed but i think concurrent task should hold grunt from running following tasks

**Comment by sindresorhus** [comment]
I don't really have time to guess what your configuration is and this issue is old. Happy to look into this further if you submit a PR with a failing test.
